languageCode = 'en-us'
theme = 'stack'

[params]    
  author = "Jonathan Alonso"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Resume"
    url = "/resume"
    weight = 2

  [[menu.main]]
    name = "Contact"
    url = "/contact"
    weight = 3